name: building-and-deployment

on:
  push:
    branches:
      - main
env:
  project_name: "automatizacion-boletia"
  language: "java"
  java-version: "18"
  java-distribution: "adopt"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-distribution }}
      - name: Install dependencies
        env:
          ARTIFACTORY_READER_USER: ${{secrets.ARTIFACTORY_READER_USER}}
          ARTIFACTORY_READER_API_KEY: ${{secrets.ARTIFACTORY_READER_API_KEY}}
        run: mvn clean install -DskipTests
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-v1
      - name: Execute Tests
        env:
          ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
          ARTIFACTORY_READER_API_KEY: ${{ secrets.ARTIFACTORY_READER_API_KEY }}
        run: mvn test -P boletia
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'https://maximus-cupones.plupets.com/'
      - name: Upload artifactory report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            reports/
            screen/
      - name: Persist Data
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
          retention-days: 1
