name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  #schedule:
    #- cron: "30 20 * * Mon"
  workflow_dispatch:
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
       contents: write
       security-events: write
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Install dependencies
      run: mvn clean install -DskipTests
    - name: Run Selenium tests
      run: mvn test
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: reports
          path: |
            reports/
            screen/
          retention-days: 1
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.13.0
      with:
        target: 'https://maximus-cupones.plupets.com/'
        artifact_name: security_reports
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore security report
      if: always()
      uses: actions/download-artifact@v3
      with:
        name: security_reports
        path: automatizacion-boletia/security-reports
